{
  config,
  pkgs,
  username,
  ...
}:

let
  # Where this repository is checked out. mkOutOfStoreSymlink needs a path that
  # exists at activation time, not a copy in the Nix store, so it cannot be
  # derived from the flake itself.
  dotfiles = "${config.home.homeDirectory}/dotfiles";

  # Symlink straight into the working tree instead of into the store, so a file
  # stays editable in place and an edit takes effect without a rebuild. That is
  # the behaviour the previous install.sh had, and the reason these configs are
  # kept as plain dotfiles rather than generated by Nix.
  link = path: config.lib.file.mkOutOfStoreSymlink "${dotfiles}/home/${path}";
in
{
  home = {
    inherit username;
    homeDirectory = "/Users/${username}";

    # Marks the home-manager release this configuration was written against.
    # It is a compatibility marker, not a version to keep current: leave it.
    stateVersion = "24.11";

    file = {
      ".zshrc".source = link ".config/zsh/.zshrc";
      ".gitconfig".source = link ".config/git/.gitconfig";
    };

    # Everything the .zshrc expects on PATH. GUI apps and fonts stay in
    # Homebrew, which handles macOS app bundles better than Nix does.
    packages = with pkgs; [
      atuin
      bat
      bottom
      delta
      direnv
      dust
      duf
      eza
      fd
      fzf
      lazygit
      mise
      procs
      ripgrep
      uv
      zoxide
    ];
  };

  xdg.configFile."wezterm/wezterm.lua".source = link ".config/wezterm/wezterm.lua";

  # Makes the home-manager command itself available.
  programs.home-manager.enable = true;
}
