{
  config,
  lib,
  pkgs,
  user,
  ...
}:

let
  # Where this repository is checked out. mkOutOfStoreSymlink needs a path that
  # exists at activation time, not a copy in the Nix store, so it cannot be
  # derived from the flake itself.
  dotfiles = "${config.home.homeDirectory}/dotfiles";

  configRoot = ./home/.config;

  relative = file: lib.removePrefix "${toString configRoot}/" (toString file);

  # home/.config mirrors ~/.config exactly, so the tree is the declaration:
  # every file under it is linked to the same path in the home directory and
  # nothing has to be listed twice. Linking is per file, never per directory,
  # so the repository never takes over a directory that also holds state
  # generated by the tool itself.
  #
  # The links point at the working tree rather than at a read-only store copy,
  # so editing a file takes effect without a rebuild.
  linkOf = file: {
    name = relative file;
    value.source = config.lib.file.mkOutOfStoreSymlink "${dotfiles}/home/.config/${relative file}";
  };

  tracked = builtins.filter (f: baseNameOf (toString f) != ".DS_Store") (
    lib.filesystem.listFilesRecursive configRoot
  );
in
{
  home = {
    username = user;
    homeDirectory = "/Users/${user}";
    stateVersion = "24.11";

    packages = with pkgs; [
      atuin
      bat
      bottom
      delta
      dust
      duf
      eza
      fd
      fzf
      gh
      go
      grpcurl
      httpie
      hyperfine
      jq
      k9s
      lazygit
      mise
      procs
      ripgrep
      tealdeer
      tmux
      zoxide

      # From the unstable input: cloud CLIs chase provider APIs, and Neovim
      # plugins target the newest release, so a release behind costs here.
      unstable.awscli2
      unstable.azure-cli
      unstable.neovim
    ];
  };

  xdg.configFile = builtins.listToAttrs (map linkOf tracked);

  programs.home-manager.enable = true;
}
