{ config, lib, ... }:

let
  # Where this repository is reachable from. mkOutOfStoreSymlink needs a path
  # that exists at activation time, not a copy in the Nix store, so it cannot be
  # derived from the flake itself. bootstrap.sh points ~/.dotfiles at wherever
  # the clone actually lives, which keeps this one line true on any machine.
  dotfiles = "${config.home.homeDirectory}/.dotfiles";

  configRoot = ./.config;

  relative = file: lib.removePrefix "${toString configRoot}/" (toString file);

  # home/.config mirrors ~/.config exactly, so the tree is the declaration:
  # every file under it is linked to the same path in the home directory and
  # nothing has to be listed twice. Linking is per file, never per directory,
  # so the repository never takes over a directory that also holds state
  # generated by the tool itself.
  #
  # The links point at the working tree rather than at a read-only store copy,
  # so editing a file takes effect without a rebuild.
  linkOf = file: {
    name = relative file;
    value.source = config.lib.file.mkOutOfStoreSymlink "${dotfiles}/home/.config/${relative file}";
  };

  # .nix is skipped so a module can sit next to the config it configures --
  # home/.config/zsh/zsh.nix would otherwise be linked into ~/.config as if it
  # were configuration for something.
  ignored = file: let name = baseNameOf (toString file); in
    name == ".DS_Store" || lib.hasSuffix ".nix" name;

  tracked = builtins.filter (f: !ignored f) (lib.filesystem.listFilesRecursive configRoot);
in
{
  xdg.configFile = builtins.listToAttrs (map linkOf tracked);
}
